import type { Recipe, ShelfConfig } from '../types'

export const mockRecipes: Recipe[] = [
  {
    title: "Grandma Marie's Tomato Sauce",
    origin: 'Grandma Marie',
    importedFrom: 'handwritten card',
    committedAt: '2024-12-24',
    version: 3,
    forkOf: null,
    tags: ['italian', 'sauce', 'family'],
    prepTime: '15 min',
    cookTime: '45 min',
    servings: 4,
    quote: 'Always use San Marzano, never anything else.',
    ingredients: [
      '800g San Marzano tomatoes, crushed by hand',
      '3 garlic cloves, sliced thin',
      '1 handful fresh basil',
      '4 tbsp olive oil',
      '1 tsp salt',
      'pinch of sugar',
    ],
    steps: [
      'Warm olive oil in a wide pan over medium heat.',
      "Add garlic, cook until just golden — don't rush it.",
      'Add tomatoes, stir to combine.',
      'Simmer uncovered for 40 minutes, stirring occasionally.',
      'Tear in basil at the last minute, adjust salt.',
    ],
    notes: 'The secret is patience on step 4. A wide pan matters — too deep and it steams instead of reducing.',
    commits: [
      { version: 1, date: '2024-03-12', message: 'Exactly as found on the card' },
      { version: 2, date: '2024-08-01', message: 'Added pinch of sugar — mellows the acidity' },
      { version: 3, date: '2024-12-24', message: 'Christmas batch — doubled it, still perfect' },
    ],
  },
  {
    title: 'Weeknight Pasta Carbonara',
    origin: 'Serious Eats',
    importedFrom: 'https://www.seriouseats.com/the-best-pasta-carbonara-recipe',
    committedAt: '2025-01-15',
    version: 1,
    forkOf: null,
    tags: ['italian', 'pasta', 'quick'],
    prepTime: '10 min',
    cookTime: '20 min',
    servings: 2,
    ingredients: [
      '200g spaghetti or rigatoni',
      '100g guanciale or pancetta, diced',
      '2 large eggs + 1 yolk',
      '50g Pecorino Romano, finely grated',
      '50g Parmigiano-Reggiano, finely grated',
      'freshly cracked black pepper',
      'kosher salt',
    ],
    steps: [
      'Bring a large pot of well-salted water to boil. Cook pasta until just shy of al dente.',
      'Meanwhile, cook guanciale in a cold pan over medium heat until fat renders and edges crisp.',
      'Whisk eggs, yolk, and both cheeses together. Season generously with pepper.',
      'Reserve 1 cup pasta water before draining.',
      'Off heat, add hot pasta to pan with guanciale. Toss to coat in fat.',
      'Pour egg mixture over pasta, adding pasta water a splash at a time, tossing constantly until glossy and saucy.',
    ],
    notes: 'Never add cream. The emulsification of eggs, fat, and starchy water is the sauce.',
    commits: [
      { version: 1, date: '2025-01-15', message: 'First commit — adapted from Serious Eats' },
    ],
  },
  {
    title: 'Shakshuka',
    origin: '@ottolenghi',
    importedFrom: 'https://www.instagram.com/p/ottolenghi-shakshuka',
    committedAt: '2025-03-02',
    version: 2,
    forkOf: null,
    tags: ['middle-eastern', 'eggs', 'brunch', 'vegetarian'],
    prepTime: '10 min',
    cookTime: '25 min',
    servings: 2,
    ingredients: [
      '2 tbsp olive oil',
      '1 onion, finely diced',
      '1 red bell pepper, diced',
      '3 garlic cloves, minced',
      '1 tsp cumin',
      '1 tsp smoked paprika',
      '½ tsp chili flakes',
      '400g crushed tomatoes',
      '4 eggs',
      'salt and pepper',
      'fresh parsley or cilantro to serve',
      'crusty bread, for mopping',
    ],
    steps: [
      'Heat olive oil in a wide, lidded skillet over medium heat.',
      'Cook onion and pepper until soft, about 8 minutes.',
      'Add garlic and spices, stir for 1 minute until fragrant.',
      'Pour in tomatoes, season, and simmer 10 minutes until thickened.',
      'Make 4 wells in the sauce and crack an egg into each.',
      'Cover and cook 5–7 minutes until whites are set but yolks still runny.',
      'Scatter herbs over the top and serve straight from the pan.',
    ],
    commits: [
      { version: 1, date: '2025-02-10', message: 'Saved from Instagram — Ottolenghi version' },
      { version: 2, date: '2025-03-02', message: 'Added smoked paprika, reduced chili — much better' },
    ],
  },
]

export const mockShelfConfig: ShelfConfig = {
  repoName: 'commeat-recipes',
  theme: 'botanical',
  cardLayout: 'portrait',
  printFormat: 'A5',
}
