import type { Recipe } from '../types'

function cell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ')
}

export function generateReadme(recipes: Recipe[], username: string): string {
  const lines: string[] = [
    `# Commeat — ${username}'s Cookbook`,
    '',
    '*"Your recipes, committed."*',
    '',
  ]

  if (recipes.length === 0) {
    lines.push(
      'No recipes yet. Add your first recipe and commit it to get started.',
      '',
    )
  } else {
    const sorted = [...recipes].sort((a, b) =>
      b.committedAt.localeCompare(a.committedAt),
    )

    lines.push('| Recipe | Origin | Tags | Last committed | Version |')
    lines.push('| --- | --- | --- | --- | --- |')

    for (const r of sorted) {
      const tags = cell(r.tags.join(', '))
      lines.push(
        `| ${cell(r.title)} | ${cell(r.origin)} | ${tags} | ${r.committedAt} | v${r.version} |`,
      )
    }

    lines.push('')
  }

  lines.push('---', '*Generated by Commeat*', '')

  return lines.join('\n')
}
