function deSlug(slug: string): string {
  return slug.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
}

function escapePipe(value: string): string {
  return value.replace(/\|/g, '\\|')
}

export function generateReadme(files: string[], username: string): string {
  const lines: string[] = [
    `# Commeat — ${username}'s Cookbook`,
    '',
    '*"Your recipes, committed."*',
    '',
  ]

  if (files.length === 0) {
    lines.push(
      'No recipes yet. Add your first recipe and commit it to get started.',
      '',
    )
  } else {
    lines.push('| Recipe | File |')
    lines.push('| --- | --- |')

    for (const path of files) {
      const slug = path.replace(/^recipes\//, '').replace(/\.md$/, '')
      const name = escapePipe(deSlug(slug))
      lines.push(`| [${name}](${escapePipe(path)}) | \`${escapePipe(path)}\` |`)
    }

    lines.push('')
  }

  lines.push('---', '*Generated by Commeat*', '')

  return lines.join('\n')
}
