import { describe, it, expect } from 'vitest'
import { generateReadme } from './readme'

describe('generateReadme', () => {
  it('renders the title and tagline for any input', () => {
    const md = generateReadme([], 'mathieu')
    expect(md).toContain("# Commeat — mathieu's Cookbook")
    expect(md).toContain('"Your recipes, committed."')
    expect(md).toContain('Generated by Commeat')
  })

  it('renders empty state correctly — no table, friendly message', () => {
    const md = generateReadme([], 'mathieu')
    expect(md).toContain('No recipes yet')
    expect(md).not.toContain('| Recipe |')
    expect(md).not.toContain('| --- |')
  })

  it('renders a table with the correct headers for non-empty input', () => {
    const md = generateReadme(['recipes/tomato-sauce.md'], 'mathieu')
    expect(md).toContain('| Recipe | File |')
    expect(md).toContain('| --- | --- |')
  })

  it('derives readable names from file slugs', () => {
    const md = generateReadme(['recipes/grandmas-tomato-sauce.md'], 'mathieu')
    expect(md).toContain('Grandmas Tomato Sauce')
  })

  it('includes a row for every file', () => {
    const files = [
      'recipes/tomato-sauce.md',
      'recipes/carbonara.md',
      'recipes/shakshuka.md',
    ]
    const md = generateReadme(files, 'mathieu')
    expect(md).toContain('Tomato Sauce')
    expect(md).toContain('Carbonara')
    expect(md).toContain('Shakshuka')
  })

  it('includes file paths in the table', () => {
    const md = generateReadme(['recipes/tomato-sauce.md'], 'mathieu')
    expect(md).toContain('recipes/tomato-sauce.md')
  })

  it('escapes pipe characters in cell values', () => {
    const md = generateReadme(['recipes/sauce-classic.md'], 'mathieu')
    const tableRows = md.split('\n').filter((l) => l.startsWith('|') && !l.startsWith('| ---'))
    for (const row of tableRows) {
      const cells = row.split('|').filter(Boolean)
      expect(cells.length).toBeGreaterThanOrEqual(2)
    }
  })
})
